### ISSUE TITLE
All of my previous parses are gone

### ISSUE THREAD

**Issue by NoobMove99** [Solinur/CombatMetrics#7]
Hey man,

I got some new gear and decided to parse afterwards I went to save the parse and I saw that all of my other parses are gone.
Can I find them in a file anywhere or are they just gone?

**Comment by Solinur** [comment]
Sorry , somehow this slipped trough. 

Generally, when parses are gone, ESO failed to load the SavedVariable file. Most cases seem to be related to Antivirus blocking access to the file, hard disc issues or using onedrive on the folder, where the file is located. 

When it happens, you can try to backup the SavedVariable folder before logging out or reloading UI. Because then the files are overwritten with whatever is present ingame (=in RAM) and if write access is possible, it might overwrite your saved parses.

All this is not an issue created by AddOns btw, the whole load/write process is fixed by ZOS without any access via API.
